[package]
name = "rouge_software"
version = "0.1.0"
edition = "2024"

[dependencies]
adw = { version = "0.7.2", package = "libadwaita", features = ["v1_6"] }
gtk4 = { version = "0.9.6", features = ["gnome_47"] }
